/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateTripRouteImport } from './routes/create-trip'
import { Route as BuildItineraryRouteImport } from './routes/build-itinerary'
import { Route as AiPlannerRouteImport } from './routes/ai-planner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItineraryBuilderTripIdRouteImport } from './routes/itinerary-builder.$tripId'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTripRoute = CreateTripRouteImport.update({
  id: '/create-trip',
  path: '/create-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildItineraryRoute = BuildItineraryRouteImport.update({
  id: '/build-itinerary',
  path: '/build-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlannerRoute = AiPlannerRouteImport.update({
  id: '/ai-planner',
  path: '/ai-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryBuilderTripIdRoute = ItineraryBuilderTripIdRouteImport.update({
  id: '/itinerary-builder/$tripId',
  path: '/itinerary-builder/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-planner': typeof AiPlannerRoute
  '/build-itinerary': typeof BuildItineraryRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/invoice': typeof InvoiceRoute
  '/itinerary': typeof ItineraryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-trips': typeof MyTripsRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/itinerary-builder/$tripId': typeof ItineraryBuilderTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-planner': typeof AiPlannerRoute
  '/build-itinerary': typeof BuildItineraryRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/invoice': typeof InvoiceRoute
  '/itinerary': typeof ItineraryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-trips': typeof MyTripsRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/itinerary-builder/$tripId': typeof ItineraryBuilderTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-planner': typeof AiPlannerRoute
  '/build-itinerary': typeof BuildItineraryRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/invoice': typeof InvoiceRoute
  '/itinerary': typeof ItineraryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-trips': typeof MyTripsRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/itinerary-builder/$tripId': typeof ItineraryBuilderTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-planner'
    | '/build-itinerary'
    | '/create-trip'
    | '/dashboard'
    | '/invoice'
    | '/itinerary'
    | '/landing'
    | '/login'
    | '/map'
    | '/my-trips'
    | '/packing'
    | '/profile'
    | '/register'
    | '/search'
    | '/trips'
    | '/itinerary-builder/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-planner'
    | '/build-itinerary'
    | '/create-trip'
    | '/dashboard'
    | '/invoice'
    | '/itinerary'
    | '/landing'
    | '/login'
    | '/map'
    | '/my-trips'
    | '/packing'
    | '/profile'
    | '/register'
    | '/search'
    | '/trips'
    | '/itinerary-builder/$tripId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-planner'
    | '/build-itinerary'
    | '/create-trip'
    | '/dashboard'
    | '/invoice'
    | '/itinerary'
    | '/landing'
    | '/login'
    | '/map'
    | '/my-trips'
    | '/packing'
    | '/profile'
    | '/register'
    | '/search'
    | '/trips'
    | '/itinerary-builder/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiPlannerRoute: typeof AiPlannerRoute
  BuildItineraryRoute: typeof BuildItineraryRoute
  CreateTripRoute: typeof CreateTripRoute
  DashboardRoute: typeof DashboardRoute
  InvoiceRoute: typeof InvoiceRoute
  ItineraryRoute: typeof ItineraryRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MyTripsRoute: typeof MyTripsRoute
  PackingRoute: typeof PackingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  TripsRoute: typeof TripsRoute
  ItineraryBuilderTripIdRoute: typeof ItineraryBuilderTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-trip': {
      id: '/create-trip'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof CreateTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-itinerary': {
      id: '/build-itinerary'
      path: '/build-itinerary'
      fullPath: '/build-itinerary'
      preLoaderRoute: typeof BuildItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-planner': {
      id: '/ai-planner'
      path: '/ai-planner'
      fullPath: '/ai-planner'
      preLoaderRoute: typeof AiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary-builder/$tripId': {
      id: '/itinerary-builder/$tripId'
      path: '/itinerary-builder/$tripId'
      fullPath: '/itinerary-builder/$tripId'
      preLoaderRoute: typeof ItineraryBuilderTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiPlannerRoute: AiPlannerRoute,
  BuildItineraryRoute: BuildItineraryRoute,
  CreateTripRoute: CreateTripRoute,
  DashboardRoute: DashboardRoute,
  InvoiceRoute: InvoiceRoute,
  ItineraryRoute: ItineraryRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MyTripsRoute: MyTripsRoute,
  PackingRoute: PackingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  TripsRoute: TripsRoute,
  ItineraryBuilderTripIdRoute: ItineraryBuilderTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
